# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apps/calendar_notes/templates/calendar_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarNotes(object):
    def setupUi(self, CalendarNotes):
        CalendarNotes.setObjectName("CalendarNotes")
        CalendarNotes.resize(1129, 739)
        self.calendarWidget = QtWidgets.QCalendarWidget(CalendarNotes)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 60, 561, 551))
        self.calendarWidget.setObjectName("calendarWidget")
        self.timeEdit = QtWidgets.QTimeEdit(CalendarNotes)
        self.timeEdit.setGeometry(QtCore.QRect(10, 10, 561, 41))
        self.timeEdit.setObjectName("timeEdit")
        self.listWidget = QtWidgets.QListWidget(CalendarNotes)
        self.listWidget.setGeometry(QtCore.QRect(585, 111, 531, 611))
        self.listWidget.setObjectName("listWidget")
        self.layoutWidget = QtWidgets.QWidget(CalendarNotes)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 620, 571, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.event_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.event_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.event_lineEdit.setObjectName("event_lineEdit")
        self.verticalLayout.addWidget(self.event_lineEdit)
        self.add_event_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_event_button.setMinimumSize(QtCore.QSize(0, 50))
        self.add_event_button.setObjectName("add_event_button")
        self.verticalLayout.addWidget(self.add_event_button)
        self.to_main_menu_button = QtWidgets.QPushButton(CalendarNotes)
        self.to_main_menu_button.setGeometry(QtCore.QRect(1010, 50, 113, 50))
        self.to_main_menu_button.setMinimumSize(QtCore.QSize(0, 50))
        self.to_main_menu_button.setObjectName("to_main_menu_button")
        self.connect_tg_bot_button = QtWidgets.QPushButton(CalendarNotes)
        self.connect_tg_bot_button.setGeometry(QtCore.QRect(750, 10, 121, 41))
        self.connect_tg_bot_button.setObjectName("connect_tg_bot_button")
        self.turn_on_radioButton = QtWidgets.QRadioButton(CalendarNotes)
        self.turn_on_radioButton.setGeometry(QtCore.QRect(760, 60, 111, 20))
        self.turn_on_radioButton.setObjectName("turn_on_radioButton")
        self.layoutWidget1 = QtWidgets.QWidget(CalendarNotes)
        self.layoutWidget1.setGeometry(QtCore.QRect(580, 10, 110, 95))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_utc_label = QtWidgets.QLabel(self.layoutWidget1)
        self.choose_utc_label.setObjectName("choose_utc_label")
        self.verticalLayout_2.addWidget(self.choose_utc_label)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_2.addWidget(self.comboBox)

        self.retranslateUi(CalendarNotes)
        QtCore.QMetaObject.connectSlotsByName(CalendarNotes)

    def retranslateUi(self, CalendarNotes):
        _translate = QtCore.QCoreApplication.translate
        CalendarNotes.setWindowTitle(_translate("CalendarNotes", "Dialog"))
        self.add_event_button.setText(_translate("CalendarNotes", "Add event"))
        self.to_main_menu_button.setText(_translate("CalendarNotes", "<- Back"))
        self.connect_tg_bot_button.setText(_translate("CalendarNotes", "Connect TgBot"))
        self.turn_on_radioButton.setText(_translate("CalendarNotes", "Turn on"))
        self.choose_utc_label.setText(_translate("CalendarNotes", "<html><head/><body><p align=\"center\">Choose GMT</p></body></html>"))
