# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apps/text_notes/templates/list_text_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListTextNotes(object):
    def setupUi(self, ListTextNotes):
        ListTextNotes.setObjectName("ListTextNotes")
        ListTextNotes.resize(616, 586)
        self.to_main_menu_button = QtWidgets.QPushButton(ListTextNotes)
        self.to_main_menu_button.setGeometry(QtCore.QRect(0, 30, 111, 41))
        self.to_main_menu_button.setObjectName("to_main_menu_button")
        self.add_folder_button = QtWidgets.QPushButton(ListTextNotes)
        self.add_folder_button.setGeometry(QtCore.QRect(0, 110, 111, 41))
        self.add_folder_button.setObjectName("add_folder_button")
        self.scrollArea = QtWidgets.QScrollArea(ListTextNotes)
        self.scrollArea.setGeometry(QtCore.QRect(109, 19, 491, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.change_title_button = QtWidgets.QPushButton(ListTextNotes)
        self.change_title_button.setGeometry(QtCore.QRect(0, 160, 111, 41))
        self.change_title_button.setObjectName("change_title_button")
        self.delete_folder_button = QtWidgets.QPushButton(ListTextNotes)
        self.delete_folder_button.setGeometry(QtCore.QRect(0, 210, 111, 41))
        self.delete_folder_button.setObjectName("delete_folder_button")

        self.not_unique_title_status_bar = QtWidgets.QStatusBar(ListTextNotes)
        self.not_unique_title_status_bar.setObjectName("statusbar")
        ListTextNotes.setStatusBar(self.not_unique_title_status_bar)

        self.retranslateUi(ListTextNotes)
        QtCore.QMetaObject.connectSlotsByName(ListTextNotes)

    def retranslateUi(self, ListTextNotes):
        _translate = QtCore.QCoreApplication.translate
        ListTextNotes.setWindowTitle(_translate("ListTextNotes", "Dialog"))
        self.to_main_menu_button.setText(_translate("ListTextNotes", "<- Back"))
        self.add_folder_button.setText(_translate("ListTextNotes", "Add folder"))
        self.change_title_button.setText(_translate("ListTextNotes", "Change title"))
        self.delete_folder_button.setText(_translate("ListTextNotes", "Delete folder"))
