# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apps/table_notes/templates/list_table_notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListTableNotes(object):
    def setupUi(self, ListTableNotes):
        ListTableNotes.setObjectName("ListTableNotes")
        ListTableNotes.resize(727, 701)
        self.scrollArea = QtWidgets.QScrollArea(ListTableNotes)
        self.scrollArea.setGeometry(QtCore.QRect(19, 9, 691, 611))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 689, 609))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.to_main_main_button = QtWidgets.QPushButton(ListTableNotes)
        self.to_main_main_button.setGeometry(QtCore.QRect(10, 630, 113, 41))
        self.to_main_main_button.setObjectName("to_main_main_button")
        self.layoutWidget = QtWidgets.QWidget(ListTableNotes)
        self.layoutWidget.setGeometry(QtCore.QRect(380, 630, 336, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_table_button = QtWidgets.QPushButton(self.layoutWidget)
        self.add_table_button.setMinimumSize(QtCore.QSize(40, 40))
        self.add_table_button.setObjectName("add_table_button")
        self.horizontalLayout.addWidget(self.add_table_button)
        self.change_title_of_the_table_button = QtWidgets.QPushButton(self.layoutWidget)
        self.change_title_of_the_table_button.setMinimumSize(QtCore.QSize(40, 40))
        self.change_title_of_the_table_button.setObjectName("change_title_of_the_table_button")
        self.horizontalLayout.addWidget(self.change_title_of_the_table_button)
        self.delete_table_button = QtWidgets.QPushButton(self.layoutWidget)
        self.delete_table_button.setMinimumSize(QtCore.QSize(40, 40))
        self.delete_table_button.setObjectName("delete_table_button")
        self.horizontalLayout.addWidget(self.delete_table_button)

        self.retranslateUi(ListTableNotes)
        QtCore.QMetaObject.connectSlotsByName(ListTableNotes)

    def retranslateUi(self, ListTableNotes):
        _translate = QtCore.QCoreApplication.translate
        ListTableNotes.setWindowTitle(_translate("ListTableNotes", "Dialog"))
        self.to_main_main_button.setText(_translate("ListTableNotes", "<- Back"))
        self.add_table_button.setText(_translate("ListTableNotes", "Add table"))
        self.change_title_of_the_table_button.setText(_translate("ListTableNotes", "Change title"))
        self.delete_table_button.setText(_translate("ListTableNotes", "Delete table"))
